steps:
  - label: ":hammer: Linting"
    command:
      - cd app && bundle install
      - rubocop -l
    plugins:
      - docker#v5.10.0:
          image: ruby:3.3.1

  - label: ":rspec: Snapshot Testing"
    command:
      - cd app && bundle install
      - rspec spec
    plugins:
      - docker#v5.10.0:
          image: ruby:3.3.1
          workdir: /app
