steps:
  - label: ":hammer: Testing"
    command: rubocop -l .
    plugins:
      - docker-compose#v4.14.0:
          run: app
  - label: ":rspec:"
    command: rspec
    plugins:
      - docker-compose#v4.14.0:
          run: app