steps:
  - label: ":hammer: Testing"
    command: gem install rubocop && rubocop -l app
    plugins:
      - docker#v5.7.0:
          image: ruby:3.4

  - wait: ~

  - label: ":rspec:"
    command: bundle install && bundle exec rspec --color specs
    plugins:
      - docker#v5.7.0:
          image: ruby:3.4

  - wait: ~

  - label: ":docker: Build image"
    command: docker build . -t migration