steps:
  - label: ":hammer: Testing"
    command: gem install rubocop && rubocop -l app
    plugins:
      - docker#v5.7.0:
          image: ruby:3.2 
  - label: ":rspec:"
    command: rspec
    plugins:
      - docker-compose#v4.14.0:
          run: migrator
          workdir: /app

  - wait: ~

  - label: ":docker: Build image"
    command: docker build . -t migration