steps:
  - label: ":hammer: Lint Tests"
    command: rubocop -l --auto-gen-config .
    plugins:
      - docker-compose#v4.14.0:
          run: app
  - label: ":rspec: Snapshot Tests"
    command: bundle exec rspec && rspec --color spec
    plugins:
      - docker-compose#v4.14.0:
          run: app