steps:
  # Run the tests again to make sure they pass before deploying
  - label: ":hammer: Linting"
    command:
      - cd app && bundle install
      - rubocop
    plugins:
      - docker#v5.11.0:
          image: ruby:4.0.0

  - label: ":rspec: Snapshot Testing"
    command:
      - cd app && bundle install
      - rspec spec
    plugins:
      - docker#v5.11.0:
          image: ruby:4.0.0
          workdir: /app

  - wait: ~

  - label: ":docker: :rocket: Latest"
    commands:
      - docker build . -t buildkite/migration-tool
      - docker push buildkite/migration-tool
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-migration-tool-deploy
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME: /pipelines/buildkite/migration-tool-deploy/docker-login-username
            DOCKER_LOGIN_PASSWORD: /pipelines/buildkite/migration-tool-deploy/docker-login-password
      - docker-login#v3.0.0: ~
    if: |
      build.branch == 'main'


  - label: ":docker: :rocket: Tag"
    plugins:
      - docker-login#v3.0.0: ~
    commands:
      - docker build . -t buildkite/migration-tool:${BUILDKITE_TAG}
      - docker push buildkite/migration-tool:${BUILDKITE_TAG}
    if: |
      build.tag != null
