steps:
  - label: ":hammer: Lint Tests"
    command: gem install rubocop && rubocop -l --auto-gen-config .
    plugins:
      - docker-compose#v4.14.0:
          run: app
  - label: ":rspec: Snapshot Tests"
    command: gem install rspec && rspec --color spec
    plugins:
      - docker-compose#v4.14.0:
          run: app