# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'parslet'
gem 'rack'
gem 'puma' # necessary for starting the HTTP interface
gem 'rouge'

group :development, :test do
  gem 'rspec'
  gem 'rspec-snapshot'
  gem 'rubocop'
end
